# Generated by Django 2.1 on 2019-04-07 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='occupied_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('room_number', models.IntegerField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('price_per_night', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='occupied_info',
            name='room_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.rooms'),
        ),
    ]
