# Generated by Django 2.0.2 on 2019-04-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='sallary',
            field=models.FloatField(default='1.0'),
        ),
        migrations.AddField(
            model_name='employees',
            name='sallary_factor',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
