# Generated by Django 2.0.2 on 2019-04-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20190403_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='sallary',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='sallary_factor',
            field=models.FloatField(default=1.0),
        ),
    ]
