# Generated by Django 2.0.2 on 2019-04-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20190403_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='employees_deleted',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('passportID', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=150)),
                ('employment_data', models.DateField()),
                ('firing_data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='sallary_factor',
            new_name='sallary_rate',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='sallary',
        ),
    ]
