# Generated by Django 2.1 on 2019-04-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booked_rooms',
            fields=[
                ('id_room', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('passportID', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=150)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
            ],
        ),
    ]
